### ISSUE TITLE
Allow Importing of External MIDI files

### ISSUE THREAD

**Issue by caffeinewriter** [musicope/game#16]
It'd be nice to allow importing of external MIDI files, since I have some that wouldn't be possible to include with the site itself due to copyright constraints, but I would still like to use them.

**Comment by czb** [comment]
Hi,

thanks for your comment. I do not plan to develop the game further as I mainly made it for my own needs :). I also do not plan to extend hosting for musicope.com. This github page will however remain as it is. And to be honest, you are the first one interested in the game in many years :).

I can however recommend you to
* download the game from this github page ( https://github.com/musicope/game/archive/master.zip )
* unpack it
* go to `game-master/Musicope`
* execute `mongoose-3.4.exe`
* in e.g. `chrome` go to `http://localhost:8080/`

To change the songs you can
* contents of the `songs/songs.json` to fit your needs
* alternatively you can point the game to an alternative json file e.g.: `localhost:8080/list/?l_songsUrl=../songs/private.json`

Hope it helps

**Comment by caffeinewriter** [comment]
Thanks for the reply! I'll have to give that a shot. :) Awesome job with the game as well. Not sure how difficult it would be, but you might be able to deploy it to Heroku or Openshift for free, so the hosting costs would be mitigated. I might actually try something similar to this using the upcoming MIDI APIs for the web. Anyway, awesome job on the site!

**Comment by czb** [comment]
Thanks. I will investigate the option to host the game somewhere. Is there any browser that supports the MIDI API? I also would like to get rid of the Jazz plugin.

**Comment by caffeinewriter** [comment]
Glad to help! I know the [W3 spec](http://www.w3.org/TR/webmidi/) of the MIDI API is still a Working Draft, but some browsers, e.g. Chrome, may support it experimentally in some forms. I'm not sure if Firefox nightlies support it yet, but I'll have to check into that. 

I know I found Musicope today, and thought it was pretty cool, so I'd hate to see it disappear. Regardless, thanks for all your hard work!

**Comment by czb** [comment]
I have changed into nw.js and implemented web midi api. You can find the first win-32 release in the `release` section.
