### ISSUE TITLE
Dropbox user limit reached

### ISSUE THREAD

**Issue by ThoolooExpress** [musicope/game#17]
When I tried to log on with dropbox, it said that the app user limit has been reached, and that the app developer needs to increase the user limit from the app console.  Hopefully this is as simple to fix as the notice makes it sound.

**Comment by czb** [comment]
I see. The Dropbox account was in development phase. I have applied for production in Dropbox console and lets see what happens :)

**Comment by czb** [comment]
I have changed from Dropbox to nw.js. You can download win-32 version of the game in the `release` section.
