### ISSUE TITLE
NO  sound output from my speaker but midi keyboard is detected and keys get pressed(detected)

### ISSUE THREAD

**Issue by Atharvak500** [musicope/game#20]
This game is really great!!! please continue the development..... 
all this game needs is right marketing strategies.

**Comment by czb** [comment]
thanks.

The game does not produce any sound. I just send midi messages to your keyboard and the keyboard should produce the sound. I do it this way to have zero lag.

I use the game regularly so it is alive. I just prefer playing the piano to programming the game :)

**Comment by Atharvak500** [comment]
okay got it...maybe i will make some pull requests in future .... and try to make musicope muck like synthesia
