### ISSUE TITLE
Segfault upon launch

### ISSUE THREAD

**Issue by technomancy** [musicope/game#21]
This is on Debian Jessie with Electron v1.2.4.

```
phil@enigma ~/bin/musicope-win32/app/game $ ~/bin/electron/electron index.html 
Segmentation fault
```

The docs don't really give any details on how to run the game, so I'm just guessing. Any suggestions for debugging?

**Comment by czb** [comment]
Yeah, the release section is probably outdated. Will take a look at it after summer holidays ;) You can always compile it by using `gulp` and then just copy it into electron sub-folder. Then it should work. Else try the stripped web only version I pasted in the other question.

**Comment by czb** [comment]
I have removed Electron dependency
