### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by Fedora-Master** [musicope/game#22]
When I download the files my Mac automatically decompresses the files and I'm left with an icon and a bunch of code files. How am I supposed to run it?

**Comment by bergvandenp** [comment]
I'm trying to get this project running on the mac from source. The release looks like for windows only. I'm going to fiddle around a bit to get this stuff working on a mac.

**Comment by czb** [comment]
I have removed Electron dependency. Only NodeJS is required so it should be straightforward to run it on Mac
