### ISSUE TITLE
Build errors: src\typescripts\_app.ts(12,18): error TS2304: Cannot find name '$'

### ISSUE THREAD

**Issue by cuimenc** [musicope/game#23]
Hello

Can you help with below errors when running gulp?

C:\git\game>gulp
gulp-typescript: noExternalResolve is deprecated - use noResolve instead
  The non-standard option noExternalResolve has been removed as of gulp-typescript 3.0.
  Use noResolve instead.
  More information: http://dev.ivogabe.com/gulp-typescript-3/
[20:19:23] Using gulpfile C:\git\game\gulpfile.js
[20:19:23] Starting 'default'...
[20:19:23] Starting 'clean'...
[20:19:23] Finished 'default' after 31 ms
[20:19:23] Finished 'clean' after 50 ms
[20:19:23] Starting 'vendorScripts'...
[20:19:23] Starting 'vendorCSS'...
[20:19:23] Starting 'ts'...
gulp-typescript: ts(tsProject) has been deprecated - use .pipe(tsProject(reporter)) instead
  As of gulp-typescript 3.0, .pipe(ts(tsProject)) should be written as .pipe(tsProject()).
  More information: http://dev.ivogabe.com/gulp-typescript-3/
[20:19:23] Starting 'content'...
[20:19:24] Finished 'vendorCSS' after 176 ms
[20:19:24] Finished 'content' after 265 ms
[20:19:24] Finished 'vendorScripts' after 389 ms
src\typescripts_app.ts(12,18): error TS2304: Cannot find name '$'.
src\typescripts_app.ts(13,18): error TS2304: Cannot find name '$'.
src\typescripts_app.ts(35,5): error TS2304: Cannot find name '$'.
src\typescripts_app.ts(50,9): error TS2304: Cannot find name '$'.
src\typescripts_app.ts(51,13): error TS2304: Cannot find name '$'.
src\typescripts_app.ts(52,13): error TS2304: Cannot find name '$'.
src\typescripts_app.ts(53,13): error TS2304: Cannot find name '$'.
src\typescripts_app.ts(59,17): error TS2304: Cannot find name '$'.
src\typescripts_app.ts(60,17): error TS2304: Cannot find name 'Mousetrap'.
src\typescripts_app.ts(61,26): error TS2304: Cannot find name 'jQuery'.
src\typescripts_app.ts(65,17): error TS2304: Cannot find name '$'.
src\typescripts_app.ts(66,17): error TS2304: Cannot find name '$'.
src\typescripts_app.ts(72,13): error TS2304: Cannot find name '$'.
src\typescripts_app.ts(73,13): error TS2304: Cannot find name 'Mousetrap'.
src\typescripts_app.ts(81,24): error TS2304: Cannot find name '$'.
src\typescripts_app.ts(83,24): error TS2304: Cannot find name '$'.

**Comment by EmilioRivera** [comment]
I had this issue not too long ago and realized I needed the Typescript definitions header files for jQuery, Mousetrap and the other ones. If you look, you'll see there's a tsd.json configuration files that state the modules needed. Thus : 
Have you installed tsd ?
`npm install --global tsd`
When that's done, acquire the dependencies from the configuration file :
`tsd reinstall`

If you get an error from Github API (happened once) saying the rate limit has been reached, you'll need to add a token so that tsd has access to a higher limit. Follow : https://github.com/DefinitelyTyped/tsd#tsdrc

**Comment by czb** [comment]
I have updated the repository and removed gulp dependency. Give it a try ;)
