### ISSUE TITLE
Site to download game is down.

### ISSUE THREAD

**Issue by vocreate** [musicope/game#25]
Hey czb, could you please reupload the files to the game(not the source files).

http://musicope.com/
http://www1.musicope.com/?kw=

is not working.

**Comment by czb** [comment]
I will do it after the new year ;)

**Comment by vocreate** [comment]
Thank you so much !

**Comment by czb** [comment]
I have added the compiled version into the `Release` section of this GitHub project. Let me know if it does not work for you ;).

**Comment by czb** [comment]
The website will probably be down for ever ;) If you would like to use the game, please follow the bullet points on the front page of the repository
