### ISSUE TITLE
window version in release section

### ISSUE THREAD

**Issue by iDeam0316** [musicope/game#27]
Hi, 
I downloaded the window version under the release section. 
I am able to open the musicop.exe and pick a default song. However, it doesn't play the song at all. 
Am I missing something? BTW, I am using Win7 VM

Thanks
iDeam0316

**Comment by iDeam0316** [comment]
![image](https://user-images.githubusercontent.com/29525057/27264545-6bff7a00-5446-11e7-9a93-e3367e6889ab.png)
like this :

**Comment by czb** [comment]
I have not updated the release section for very very long :). I will eventually do it but until then I recommend you to compile it on your own ;).

BTW. Under File there should be Developer Tools that could hint you what went wrong.

**Comment by czb** [comment]
The release version was removed. If you would like to run the game, please follow the bullet points on the front page of this repository
