### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by marius** [musicope/game#29]
Hi,

thank you for creating this cool game.
Could you please add a license file to the repo?
Without one it is not open source.
You can get help
here: https://help.github.com/articles/licensing-a-repository/
and here: https://choosealicense.com/

If I can help in any way, I'm happy to do so.

Thank you
Marius

**Comment by alexbrazier** [comment]
Very easy to do using this link https://github.com/musicope/game/community/license/new?branch=master&template=mit

**Comment by czb** [comment]
https://github.com/musicope/game/commit/6bebe06213a36bdf65aa610ebe516eede617e85c
